package org.softcits.pc.model;

public class MbgComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_comment.id
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_comment.pc_comment
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    private String pcComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_comment.pc_star
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    private Integer pcStar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_comment.fk
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    private Integer fk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_comment.id
     *
     * @return the value of pc_comment.id
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_comment.id
     *
     * @param id the value for pc_comment.id
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_comment.pc_comment
     *
     * @return the value of pc_comment.pc_comment
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public String getPcComment() {
        return pcComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_comment.pc_comment
     *
     * @param pcComment the value for pc_comment.pc_comment
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public void setPcComment(String pcComment) {
        this.pcComment = pcComment == null ? null : pcComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_comment.pc_star
     *
     * @return the value of pc_comment.pc_star
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public Integer getPcStar() {
        return pcStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_comment.pc_star
     *
     * @param pcStar the value for pc_comment.pc_star
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public void setPcStar(Integer pcStar) {
        this.pcStar = pcStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_comment.fk
     *
     * @return the value of pc_comment.fk
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public Integer getFk() {
        return fk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_comment.fk
     *
     * @param fk the value for pc_comment.fk
     *
     * @mbggenerated Sun Apr 15 15:32:49 CST 2018
     */
    public void setFk(Integer fk) {
        this.fk = fk;
    }
}